name: Build Audio Plugins (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      JUCE_DIR: ${{ github.workspace }}/JUCE
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Checkout JUCE
      uses: actions/checkout@v3
      with:
        repository: juce-framework/JUCE
        ref: master
        path: JUCE
      
    - name: Install basic dependencies
      run: |
        brew install xcodegen cmake
        mkdir -p bin
        
    - name: Build Plugin (script)
      run: |
        chmod +x scripts/build_plugin.sh
        ./scripts/build_plugin.sh

    - name: Archive AU Component
      run: |
        cd dist
        zip -r MoreMojo_AU.zip *.component

    - name: Archive VST3 Plugin
      run: |
        cd dist
        zip -r MoreMojo_VST3.zip *.vst3

    - name: Upload AU Component
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojo-AU-macOS
        path: dist/MoreMojo_AU.zip
        retention-days: 7

    - name: Upload VST3 Plugin
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojo-VST3-macOS
        path: dist/MoreMojo_VST3.zip
        retention-days: 7
        
    # Email notifications removed due to authentication issues
    - name: Build status
      if: always()
      run: |
        echo "Plugin build ${{ github.workflow }} completed with status: ${{ job.status }}"
        echo "See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
