name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Install basic dependencies
      run: |
        # Install xcodegen, skip cmake if it exists
        brew install xcodegen || true
        brew list cmake || brew install cmake || true
        mkdir -p bin

    - name: Build App (script)
      run: |
        chmod +x scripts/build_app.sh
        ./scripts/build_app.sh

    - name: Archive app
      run: |
        cd dist
        zip -r MoreMojoStudio.zip MoreMojoStudio.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojoStudio-macOS
        path: dist/MoreMojoStudio.zip
        retention-days: 7
        
    # Slack notification for build status
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,workflow
        text: "Build ${{ github.workflow }} completed with status: ${{ job.status }}\nSee details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
