name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'

    - name: Install basic dependencies
      run: |
        brew install xcodegen cmake
        mkdir -p bin

    - name: Build App (script)
      run: |
        chmod +x scripts/build_app.sh
        ./scripts/build_app.sh

    - name: Archive app
      run: |
        cd dist
        zip -r MoreMojoStudio.zip MoreMojoStudio.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojoStudio-macOS
        path: dist/MoreMojoStudio.zip
        retention-days: 7
        
    # Email notifications removed due to authentication issues
    - name: Build status
      if: always()
      run: |
        echo "Build ${{ github.workflow }} completed with status: ${{ job.status }}"
        echo "See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
