name: Build Audio Plugins (macOS)

on:
  push:
    branches: [ main ]
    paths:
      - 'plugin/**'
      - '.github/workflows/build_plugin_mac.yml'
      - 'Makefile'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'plugin/**'
      - '.github/workflows/build_plugin_mac.yml'
      - 'Makefile'
      - 'scripts/**'

jobs:
  build:
    runs-on: macos-latest
    env:
      JUCE_DIR: ${{ github.workspace }}/JUCE
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Checkout JUCE
      uses: actions/checkout@v3
      with:
        repository: juce-framework/JUCE
        ref: master
        path: JUCE
      
    - name: Install dependencies
      run: |
        brew install cmake
        
    - name: Build Plugin (script)
      run: |
        chmod +x scripts/build_plugin.sh
        ./scripts/build_plugin.sh

    - name: Archive AU Component
      run: |
        cd dist
        zip -r MoreMojo_AU.zip *.component

    - name: Archive VST3 Plugin
      run: |
        cd dist
        zip -r MoreMojo_VST3.zip *.vst3

    - name: Upload AU Component
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojo-AU-macOS
        path: dist/MoreMojo_AU.zip
        retention-days: 7

    - name: Upload VST3 Plugin
      uses: actions/upload-artifact@v4
      with:
        name: MoreMojo-VST3-macOS
        path: dist/MoreMojo_VST3.zip
        retention-days: 7
        
    - name: Send email notification
      if: always()  # Run even if previous steps fail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: MoreMojo Plugin Build ${{ job.status }}
        body: |
          MoreMojo Plugin Build ${{ github.workflow }} completed with status: ${{ job.status }}
          
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Artifacts available for download from the Actions page:
          - AU Component: MoreMojo-AU-macOS
          - VST3 Plugin: MoreMojo-VST3-macOS
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: MoreMojo Build Notifications <github-actions@github.com>
