name: CI Only Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up minimal build environment
        run: |
          # Create directories
          mkdir -p dist/MoreMojoStudio.app/Contents/{MacOS,Resources}
          
          # Copy assets that may exist
          if [ -d "app/Resources" ]; then
            cp -R app/Resources/* dist/MoreMojoStudio.app/Contents/Resources/ || true
          fi
          
          if [ -f "app/faceplate_layout.json" ]; then
            cp app/faceplate_layout.json dist/MoreMojoStudio.app/Contents/Resources/ || true
          fi
          
          # Create Info.plist with proper indentation for YAML
          cat > dist/MoreMojoStudio.app/Contents/Info.plist << 'PLISTEOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>MoreMojoStudio</string>
              <key>CFBundleIdentifier</key>
              <string>com.example.moremojo</string>
              <key>CFBundleName</key>
              <string>MoreMojoStudio</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>LSMinimumSystemVersion</key>
              <string>11.0</string>
              <key>NSPrincipalClass</key>
              <string>NSApplication</string>
          </dict>
          </plist>
          PLISTEOF
          
          # Create executable script
          cat > dist/MoreMojoStudio.app/Contents/MacOS/MoreMojoStudio << 'SCRIPTEOF'
          #!/bin/bash
          echo "MoreMojo Studio CI Build"
          exit 0
          SCRIPTEOF
          chmod +x dist/MoreMojoStudio.app/Contents/MacOS/MoreMojoStudio
          
          # Create PkgInfo
          echo "APPL????" > dist/MoreMojoStudio.app/Contents/PkgInfo
      
      - name: Create README
        run: |
          cat > dist/README.txt << 'READMEEOF'
          MoreMojo Studio - CI Build

          This is a CI build artifact generated by the GitHub Actions workflow.
          The app bundle is a placeholder structure only, not a compiled app.
          READMEEOF
      
      - name: Create version file
        run: |
          echo "Build date: $(date)" > dist/version.txt
          echo "Commit: ${{ github.sha }}" >> dist/version.txt
          echo "Ref: ${{ github.ref }}" >> dist/version.txt

      - name: List built artifacts
        run: find dist -type f | sort
      
      - name: Upload App artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoreMojo-CI-Build
          path: dist
          if-no-files-found: error
          retention-days: 7
          
      # Uncomment the Slack notification when webhook is configured in GitHub secrets
      # - name: Send Slack notification
      #   uses: 8398a7/action-slack@v3
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,workflow
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      # Alternative basic notification that doesn't require webhook
      - name: Job status notification
        if: always()
        run: |
          echo "::notice::CI Build completed with status ${{ job.status }}"
          echo "See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
