name: Simple Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run simple test
      run: |
        echo "Hello from test workflow!"
        ls -la
        
    - name: Output success message
      run: |
        echo "Workflow completed successfully!"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
        
    # Slack notification for build status
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,workflow
        text: "Test workflow completed with status: ${{ job.status }}\nSee details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
