name: Simple Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run simple test
      run: |
        echo "Hello from test workflow!"
        ls -la
        
    - name: Output success message
      run: |
        echo "Workflow completed successfully!"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
